---
- hosts: all
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Creating a directory for static content to be placed
      file:
        path: /var/www/html/first-site
        state: directory
        mode: 0755
    - name: Copying the web-site files
      copy:
        src: ./web-site/
        dest: /var/www/html/first-site/
    - name: Copy websites files to default Nginx location
      copy:
        src: /var/www/html/first-site/
        dest: /var/www/html/
        remote_src: true

    - name: Enable default Nginx website
      file:
        src: /etc/nginx/sites-available/default
        path: /etc/nginx/sites-enabled/default
        state: link

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted